version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  mongo:
    image: mongo
    restart: always
    ports:
      - 37017:27017

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

  app:
    build: .
    depends_on:
      - postgres
      - mongo
    restart: always
    ports:
      - 5000:5000
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MONGO_DB: ${MONGO_DB}
