version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  mongo:
    image: mongo
    restart: always

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate_full_chain.pem:/etc/nginx/ssl/cert.pem
      - ./private_key.pem:/etc/nginx/ssl/key.pem
    ports:
      - 80:80
      - 443:443

  app:
    image: kotosha/goty
    depends_on:
      - postgres
      - mongo
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MONGO_DB: ${MONGO_DB}
