export { getDataOnSubmit } from './getDataOnSubmit'
export { Validation } from './Validation'
export { sanitize } from './sanitize'
export { setCorrectStatus, setWrongStatus } from './setValidationStatus'
export { handleAuth } from './handleAuth'
export { getUserInfo } from './getUserInfo'
export { handleUserInfo } from './handleUserInfo'
export { handleUserPassword } from './handleUserPassword'
export { handleAvatar } from './handleAvatar'
